package com.bcits.works.shared;

/**
 * Abstraction over key management (B31, RB-40 §3 BYOK). The concrete implementation is chosen
 * at startup: {@link AwsKmsProvider} when {@code AWS_ACCESS_KEY_ID} is set (production BYOK),
 * {@link LocalKmsProvider} otherwise (dev/test — in-memory key store).
 *
 * <p>Key material is never logged and never passes through the service layer as plaintext — only
 * encrypted blobs and key references are stored in the database.
 */
public interface KmsProvider {

    /** Human-readable provider name for audit records. */
    String name();

    /**
     * Generates a new data encryption key for {@code workspaceId}. Returns the key material
     * as a Base64-encoded string suitable for AES-256 encryption.
     *
     * @param workspaceId tenant identifier (used as the KMS key context)
     * @return Base64-encoded 32-byte key material
     */
    String generateDataKey(String workspaceId);

    /**
     * Re-encrypts {@code ciphertext} from the old key to the new key. Both keys are identified
     * by their opaque references (KMS key ARN, key-id, or local store key). Used by
     * {@link KeyRotationService} to rotate a workspace's data key without decrypting intermediate
     * plaintext on the server.
     *
     * @param workspaceId the owning workspace (for isolation + audit context)
     * @param oldKeyRef   reference to the currently active key
     * @param newKeyRef   reference to the newly generated key
     * @param ciphertext  the currently encrypted value to re-encrypt
     * @return the same plaintext re-encrypted under {@code newKeyRef}
     */
    String reEncrypt(String workspaceId, String oldKeyRef, String newKeyRef, String ciphertext);

    // ── Per-subject data-key envelope operations (RB-40 §3 crypto-shred) ─────────────────────────
    // The per-subject DEK is the unit of crypto-shred destruction. The DEK itself is generated by the
    // caller (PiiVaultService); the KMS only wraps/unwraps it under the workspace KEK it custodies, so
    // the raw DEK and the KEK never both live in the application database (RB-40 §3 rule 2).

    /** A data key wrapped under a workspace KEK: the opaque {@code kekRef} that wrapped it plus the
     *  base64 wrapped blob. Store both; {@code kekRef} lets a later unwrap pick the right KEK even
     *  across a rotation. */
    record WrappedKey(String kekRef, String wrapped) { }

    /**
     * Envelope-encrypts (wraps) raw DEK bytes under the workspace's current KEK.
     *
     * @param workspaceId the owning workspace (KEK custody + isolation/audit context)
     * @param dek         the raw AES-256 data key bytes to wrap (never persisted in plaintext)
     * @return the KEK reference used and the wrapped blob
     */
    WrappedKey wrapDataKey(String workspaceId, byte[] dek);

    /**
     * Unwraps a DEK previously produced by {@link #wrapDataKey} under the KEK identified by
     * {@code kekRef}. Returns the raw AES-256 data key bytes.
     */
    byte[] unwrapDataKey(String workspaceId, String kekRef, String wrappedDek);

    /**
     * Rotates the workspace KEK so subsequent {@link #wrapDataKey} calls wrap under a new KEK. Old
     * wrapped DEKs stay unwrappable via their stored {@code kekRef} until they are re-wrapped
     * (see {@link KeyRotationService}). Returns the new KEK reference.
     */
    String rotateKek(String workspaceId);
}
