package com.bcits.works;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.kms.KmsClient;
import software.amazon.awssdk.services.kms.model.DataKeySpec;
import software.amazon.awssdk.services.kms.model.DecryptRequest;
import software.amazon.awssdk.services.kms.model.EnableKeyRotationRequest;
import software.amazon.awssdk.services.kms.model.EncryptRequest;
import software.amazon.awssdk.services.kms.model.GenerateDataKeyRequest;
import software.amazon.awssdk.services.kms.model.ReEncryptRequest;

import java.net.URI;
import java.util.Base64;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * AWS KMS-backed {@link KmsProvider} for production BYOK (RB-40 §3/§4, EPIC-P1-pii-vault Slice 5).
 * Active when {@code cloud.aws.credentials.access-key} is set; {@link LocalKmsProvider} is the default
 * otherwise. All prod / non-prod configuration is centralized in {@link KmsProperties}
 * ({@code pii.vault.kms.*}) and documented in {@code docs/compliance/PII-VAULT-KMS-CONFIG.md}.
 *
 * <h2>Key model</h2>
 * The per-subject DEK (the crypto-shred unit) is generated by {@link PiiVaultService}; this provider
 * only <b>wraps/unwraps</b> it under the workspace's KMS <b>KEK</b> — the customer's BYOK key
 * (<code>workspace_security_settings.byok_key_ref</code>), or the platform {@link KmsProperties#getDefaultKeyId()}
 * when a workspace has none (and for the global {@code PLATFORM}-scope user identity). The raw DEK and
 * the KEK never both live in the database (RB-40 §3 rule 2): only the wrapped blob + the KEK reference
 * are stored, and the KEK never leaves KMS. <b>Region pinning:</b> when the key reference is a
 * region-qualified ARN ({@code arn:aws:kms:<region>:...}) the client is built for that region, so each
 * workspace's keys stay in their declared residency region; otherwise {@link KmsProperties#getRegion()}.
 *
 * <h2>Crypto-shred</h2>
 * Destroying a subject's {@code subject_data_keys} row (the wrapped DEK) is sufficient — the DEK is
 * unrecoverable without it, so any lingering ciphertext (incl. backups) is permanently undecryptable.
 * The KMS KEK itself is shared per workspace and is rotated, not destroyed, by {@link #rotateKek}.
 *
 * <p>Non-prod validation runs the exact code path against LocalStack KMS (see {@code PiiVaultKmsLocalStackIT}).
 */
@Component
@ConditionalOnProperty(name = "cloud.aws.credentials.access-key")
public class AwsKmsProvider implements KmsProvider {

    private static final Logger log = LoggerFactory.getLogger(AwsKmsProvider.class);

    /** Builds a {@link KmsClient} for a region — the seam tests override (LocalStack endpoint / a mock). */
    @FunctionalInterface
    public interface KmsClientFactory {
        KmsClient create(Region region);
    }

    private final KmsProperties props;
    private final WorkspaceSecuritySettingsRepository securitySettings;
    private final KmsClientFactory clientFactory;
    private final Map<String, KmsClient> clientsByRegion = new ConcurrentHashMap<>();

    /** Spring bean: a real client factory from {@link KmsProperties} (endpoint override + static creds
     *  for non-prod/LocalStack, else the default AWS credential chain). */
    public AwsKmsProvider(KmsProperties props, WorkspaceSecuritySettingsRepository securitySettings) {
        this(props, securitySettings, defaultFactory(props));
    }

    /** Injectable-factory constructor for tests (LocalStack-pointed or a mock {@link KmsClient}). */
    public AwsKmsProvider(KmsProperties props, WorkspaceSecuritySettingsRepository securitySettings,
                          KmsClientFactory clientFactory) {
        this.props = props;
        this.securitySettings = securitySettings;
        this.clientFactory = clientFactory;
    }

    private static KmsClientFactory defaultFactory(KmsProperties props) {
        return region -> {
            var builder = KmsClient.builder().region(region);
            if (props.hasEndpointOverride()) {
                // Non-prod (e.g. LocalStack): explicit endpoint + static credentials.
                builder.endpointOverride(URI.create(props.getEndpointOverride()))
                       .credentialsProvider(StaticCredentialsProvider.create(
                           AwsBasicCredentials.create(props.getAccessKey(), props.getSecretKey())));
            } else {
                // Prod: the default AWS credential chain (instance role / env / profile).
                builder.credentialsProvider(DefaultCredentialsProvider.create());
            }
            return builder.build();
        };
    }

    @Override
    public String name() {
        return "aws-kms";
    }

    // ── Per-subject DEK envelope (the live crypto-shred path) ────────────────────────────────────

    @Override
    public WrappedKey wrapDataKey(String workspaceId, byte[] dek) {
        String keyId = resolveKeyId(workspaceId);
        var resp = clientFor(keyId).encrypt(EncryptRequest.builder()
                .keyId(keyId)
                .plaintext(SdkBytes.fromByteArray(dek))
                .build());
        // kekRef = the KMS key id/ARN that wrapped the DEK, so a later unwrap targets the same key.
        return new WrappedKey(keyId, Base64.getEncoder().encodeToString(resp.ciphertextBlob().asByteArray()));
    }

    @Override
    public byte[] unwrapDataKey(String workspaceId, String kekRef, String wrappedDek) {
        var resp = clientFor(kekRef).decrypt(DecryptRequest.builder()
                .keyId(kekRef)
                .ciphertextBlob(SdkBytes.fromByteArray(Base64.getDecoder().decode(wrappedDek)))
                .build());
        return resp.plaintext().asByteArray();
    }

    @Override
    public String rotateKek(String workspaceId) {
        // BYOK rotation is AWS-managed: enable annual rotation of the key material; the ARN (and thus
        // the stored kekRef) is unchanged and old wrapped DEKs stay decryptable. KeyRotationService
        // then re-wraps each subject DEK so new material is used going forward.
        String keyId = resolveKeyId(workspaceId);
        clientFor(keyId).enableKeyRotation(EnableKeyRotationRequest.builder().keyId(keyId).build());
        log.info("[AWS-KMS] Enabled key rotation for workspace={} keyId={}", workspaceId, keyId);
        return keyId;
    }

    // ── Legacy per-workspace-key path (no live callers; kept for the KmsProvider contract) ────────

    @Override
    public String generateDataKey(String workspaceId) {
        String keyId = resolveKeyId(workspaceId);
        var resp = clientFor(keyId).generateDataKey(GenerateDataKeyRequest.builder()
                .keyId(keyId)
                .keySpec(DataKeySpec.AES_256)
                .build());
        return Base64.getEncoder().encodeToString(resp.plaintext().asByteArray());
    }

    @Override
    public String reEncrypt(String workspaceId, String oldKeyRef, String newKeyRef, String ciphertext) {
        var resp = clientFor(newKeyRef).reEncrypt(ReEncryptRequest.builder()
                .ciphertextBlob(SdkBytes.fromByteArray(Base64.getDecoder().decode(ciphertext)))
                .sourceKeyId(oldKeyRef)
                .destinationKeyId(newKeyRef)
                .build());
        return Base64.getEncoder().encodeToString(resp.ciphertextBlob().asByteArray());
    }

    // ── helpers ──────────────────────────────────────────────────────────────────────────────────

    /** The KMS key id/ARN for a workspace: its BYOK key, else the platform default. */
    private String resolveKeyId(String workspaceId) {
        String byok = securitySettings.findById(workspaceId)
                .map(WorkspaceSecuritySettings::getByokKeyRef)
                .filter(ref -> ref != null && !ref.isBlank())
                .orElse(null);
        if (byok != null) {
            return byok;
        }
        if (props.getDefaultKeyId() != null && !props.getDefaultKeyId().isBlank()) {
            return props.getDefaultKeyId();
        }
        throw new IllegalStateException(
            "No KMS key for workspace '" + workspaceId + "': set workspace_security_settings.byok_key_ref "
                + "or pii.vault.kms.default-key-id (see docs/compliance/PII-VAULT-KMS-CONFIG.md).");
    }

    /** A cached client for the key's region — pinned from the ARN when present, else the configured default. */
    private KmsClient clientFor(String keyId) {
        return clientsByRegion.computeIfAbsent(regionOf(keyId), r -> clientFactory.create(Region.of(r)));
    }

    /** Extract the region from a KMS key ARN ({@code arn:aws:kms:<region>:acct:key/id}); else the default. */
    private String regionOf(String keyId) {
        if (keyId != null && keyId.startsWith("arn:")) {
            String[] parts = keyId.split(":");
            if (parts.length > 3 && !parts[3].isBlank()) {
                return parts[3];
            }
        }
        return props.getRegion();
    }
}
