ALTER TABLE chat_conversations
ADD COLUMN IF NOT EXISTS conversation_type VARCHAR(50) NOT NULL DEFAULT 'SUPPORT';

ALTER TABLE chat_messages
ADD COLUMN IF NOT EXISTS artifact_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS artifact_ref VARCHAR(255);
